# Generated by Django 5.1.1 on 2025-05-11 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_options_alter_location_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='created_ad',
            new_name='created_at',
        ),
    ]
