# Generated by Django 5.1.1 on 2025-06-02 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_comments_comment_comments_add_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='add_comment',
            new_name='post',
        ),
    ]
